title = "Livs Blog"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "let your writing speak louder than your words"
    author = "Liv"
    description = "Some description"
    logoBig = "/images/livlu-logo.png"
    logoSmall = "/images/livlu-logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/livlu.png"
    highlightJS = true
    copyright = false
    credit = false
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false

[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 1